---
galaxy_info:
  role_name: eveng
  author: HybridOps.Tech
  description: Automated EVE-NG installation and configuration
  company: HybridOps

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - jammy  # 22.04

  galaxy_tags:
    - networking
    - emulation
    - eveng
    - virtualization
    - networkautomation
    - lab
    - cisco
    - juniper
    - kvm

dependencies: []
