# file: roles/eveng_labs/tasks/source-remote.yml
# purpose: Stage labs from remote host
# maintainer: HybridOps.Tech

- name: Clear staging directory
  file:
    path: "{{ eveng_labs_staging_dir }}"
    state: absent

- name: Recreate staging directory
  file:
    path: "{{ eveng_labs_staging_dir }}"
    state: directory
    mode: '0755'

- name: Stage labs from remote path
  synchronize:
    src: "{{ eveng_labs_remote_path }}/"
    dest: "{{ eveng_labs_staging_dir }}/"
    rsync_opts: "{{ eveng_labs_sync_exclude_patterns | default([]) }}"
  delegate_to: "{{ eveng_labs_remote_host | default(inventory_hostname) }}"
