---
galaxy_info:
  role_name: pgbackrest_repo
  author: HybridOps.Studio
  description: "Normalize pgBackRest repo settings for Autobase (S3, GCS, or Azure Blob)."
  license: "MIT"
  min_ansible_version: "2.16"

dependencies: []
