---
- name: Configure minimal PHP limits
  ansible.builtin.lineinfile:
    path: >-
      /etc/php/{{ ansible_distribution_major_version | int >= 22 | ternary('8.1', '7.4') }}/apache2/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: '^upload_max_filesize'
      line: "upload_max_filesize = 500M"
    - regexp: '^post_max_size'
      line: "post_max_size = 500M"
    - regexp: '^max_execution_time'
      line: "max_execution_time = 600"
    - regexp: '^memory_limit'
      line: "memory_limit = 512M"
  notify: restart apache2
