---
galaxy_info:
  role_name: eveng_labs
  namespace: hybridops
  author: HybridOps.Tech
  description: >-
    Deploy and manage EVE-NG lab topologies under /opt/unetlab/labs
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - networking
    - eveng
    - labs
    - network-automation

dependencies: []
