---
# Installation
eveng_force_reinstall: false
eveng_resource_profile: standard # minimal | standard | performance
eveng_environment_name: ""

# Install behaviour
eveng_install_async: false
eveng_install_async_timeout: 3600
eveng_install_async_poll: 30

# Network
eveng_hostname: "{{ inventory_hostname }}"
eveng_domain: "lab.local"
eveng_bypass_wizard: true

# PHP
eveng_configure_php: true
eveng_php_upload_max: "2G"
eveng_php_post_max: "2G"
eveng_php_max_execution: "600"
eveng_php_memory_limit: "512M"

# System
eveng_configure_sysctl: true
eveng_disable_swap: true

# Authentication
eveng_db_password: ""
eveng_root_password: "{{ lookup('env', 'EVENG_ROOT_PASSWORD') | default('eve', true) }}"
eveng_admin_password: "{{ lookup('env', 'EVENG_ADMIN_PASSWORD') | default('eve', true) }}"
eveng_users: []

# Example:
# eveng_users:
#   - username: john.doe
#     name: John Doe
#     email: john@example.com
#     password: "{{ vault_password }}"
#     role: user  # user or admin
#   - username:  jane.admin
#     name: Jane Admin
#     email: jane@example.com
#     password: "{{ vault_password }}"
#     role: admin
