---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: ssh

platforms:
  - name: eveng-molecule-test

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          eveng-molecule-test:
            ansible_host: "${MOLECULE_TEST_HOST:-localhost}"
            ansible_user: "${MOLECULE_TEST_USER:-hybridops}"
  env:
    ANSIBLE_VERBOSITY: 1

verifier:
  name: ansible

scenario:
  test_sequence:
    - syntax
    - converge
    - verify
