---
galaxy_info:
  role_name: eveng_healthcheck
  author: HybridOps Team
  description: Health check and validation for EVE-NG installations
  company: HybridOps
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - networking
    - eveng
    - monitoring
    - validation
    - healthcheck

dependencies: []
