"""Module CLI commands."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
from typing import Any

import yaml

from hyops.commands._apply_helpers import rerun_inputs_path
from hyops.runtime.exitcodes import OPERATOR_ERROR
from hyops.runtime.gcp import normalize_billing_account_id
from hyops.runtime.kv import read_kv_file
from hyops.runtime.layout import ensure_layout
from hyops.runtime.readiness import read_marker
from hyops.runtime.refs import normalize_module_ref
from hyops.runtime.root import require_runtime_selection
from hyops.runtime.module_state import normalize_state_instance
from hyops.runtime.source_roots import resolve_module_root
from hyops.runtime.state import write_text_atomic


def _load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"invalid YAML object: {path}")
    return data


def _resolve_module_dir(module_root: Path, module_ref: str) -> Path:
    normalized = normalize_module_ref(module_ref)
    if not normalized:
        raise ValueError("module_ref is required")
    module_dir = (module_root / normalized).resolve()
    spec_path = module_dir / "spec.yml"
    if not spec_path.exists():
        raise FileNotFoundError(f"spec not found: {spec_path}")
    return module_dir


def _find_example_candidates(module_dir: Path) -> list[Path]:
    preferred = [
        "examples/inputs.state.yml",
        "examples/inputs.min.yml",
        "examples/inputs.typical.yml",
        "examples/inputs.primary.yml",
        "examples/inputs.secondary.yml",
        "examples/inputs.enterprise.yml",
        "examples/inputs.burst.yml",
        "examples/inputs.dr.yml",
        "tests/example-inputs.yml",
    ]
    out: list[Path] = []
    seen: set[Path] = set()
    for rel in preferred:
        candidate = (module_dir / rel).resolve()
        if candidate.exists() and candidate not in seen:
            seen.add(candidate)
            out.append(candidate)

    examples_dir = module_dir / "examples"
    if examples_dir.exists():
        for candidate in sorted(examples_dir.glob("*.yml")) + sorted(examples_dir.glob("*.yaml")):
            resolved = candidate.resolve()
            if resolved not in seen:
                seen.add(resolved)
                out.append(resolved)

    tests_candidate = (module_dir / "tests" / "example-inputs.yml").resolve()
    if tests_candidate.exists() and tests_candidate not in seen:
        out.append(tests_candidate)
    return out


def _resolve_source_file(module_dir: Path, source: str) -> Path:
    raw = str(source or "").strip()
    if not raw:
        raise ValueError("source template is empty")
    candidate = Path(raw).expanduser()
    if not candidate.is_absolute():
        candidate = (module_dir / candidate).resolve()
    else:
        candidate = candidate.resolve()
    if not candidate.exists():
        raise FileNotFoundError(f"module input template not found: {candidate}")
    return candidate


def _defaults_payload(module_dir: Path) -> dict[str, Any]:
    spec = _load_yaml(module_dir / "spec.yml")
    raw_inputs = spec.get("inputs") or {}
    if raw_inputs and not isinstance(raw_inputs, dict):
        raise ValueError("spec.inputs must be a mapping")
    defaults = raw_inputs.get("defaults") or {}
    if defaults and not isinstance(defaults, dict):
        raise ValueError("spec.inputs.defaults must be a mapping")
    return dict(defaults)


def _render_defaults_yaml(module_ref: str, payload: dict[str, Any]) -> str:
    header = (
        f"# Generated by `hyops module init` for {module_ref}.\n"
        "# This module has no shipped example input overlay, so this file starts from\n"
        "# spec.inputs.defaults. Fill in required operator-specific values before apply.\n"
    )
    body = yaml.safe_dump(payload, sort_keys=False)
    return f"{header}{body}"


def _load_gcp_init_context(paths) -> dict[str, str]:
    context: dict[str, str] = {}

    cfg_path = paths.config_dir / "gcp.conf"
    if cfg_path.exists():
        try:
            cfg = read_kv_file(cfg_path)
        except Exception:
            cfg = {}
        context["project_id"] = str(cfg.get("GCP_PROJECT_ID") or "").strip()
        context["region"] = str(cfg.get("GCP_REGION") or "").strip()
        context["billing_account_id"] = normalize_billing_account_id(str(cfg.get("GCP_BILLING_ACCOUNT_ID") or "").strip())

    ready_path = paths.meta_dir / "gcp.ready.json"
    if ready_path.exists():
        try:
            marker = read_marker(ready_path)
        except Exception:
            marker = {}
        marker_context = marker.get("context") if isinstance(marker, dict) else {}
        if isinstance(marker_context, dict):
            project_id = str(marker_context.get("project_id") or "").strip()
            region = str(marker_context.get("region") or "").strip()
            billing_account_id = normalize_billing_account_id(str(marker_context.get("billing_account_id") or "").strip())
            if project_id:
                context["project_id"] = project_id
            if region:
                context["region"] = region
            if billing_account_id:
                context["billing_account_id"] = billing_account_id

    return context


def _detect_gcp_org_placement() -> dict[str, str]:
    """Best-effort discovery of org placement for project-factory scaffolding.

    Rules:
    - If exactly one organization is visible and no folders are visible under it,
      prefill org_id.
    - If folders are visible, do not guess; the operator should choose.
    - On any failure, return no placement.
    """

    try:
        orgs_proc = subprocess.run(
            ["gcloud", "organizations", "list", "--format=json"],
            text=True,
            capture_output=True,
            check=False,
        )
        if int(orgs_proc.returncode) != 0:
            return {}
        orgs = json.loads(orgs_proc.stdout or "[]")
        if not isinstance(orgs, list) or len(orgs) != 1:
            return {}
        org_name = str((orgs[0] or {}).get("name") or "").strip()
        if not org_name.startswith("organizations/"):
            return {}
        org_id = org_name.split("/", 1)[1].strip()
        if not org_id:
            return {}
        folders_proc = subprocess.run(
            [
                "gcloud",
                "resource-manager",
                "folders",
                "list",
                f"--organization={org_id}",
                "--format=json",
            ],
            text=True,
            capture_output=True,
            check=False,
        )
        if int(folders_proc.returncode) != 0:
            return {}
        folders = json.loads(folders_proc.stdout or "[]")
        if isinstance(folders, list) and len(folders) == 0:
            return {"org_id": org_id}
    except Exception:
        return {}
    return {}


def _enrich_project_factory_payload(
    payload: dict[str, Any],
    *,
    paths,
    env_name: str,
) -> dict[str, Any]:
    next_payload = dict(payload)
    gcp_context = _load_gcp_init_context(paths)

    context_id = str(env_name or "").strip()
    if context_id:
        next_payload["context_id"] = context_id

    project_id = str(gcp_context.get("project_id") or "").strip()
    if project_id:
        next_payload["project_id"] = project_id

    region = str(gcp_context.get("region") or "").strip()
    if region:
        next_payload["region"] = region

    billing_account_id = str(gcp_context.get("billing_account_id") or "").strip()
    if billing_account_id:
        next_payload["billing_account_id"] = billing_account_id

    if not str(next_payload.get("org_id") or "").strip() and not str(next_payload.get("folder_id") or "").strip():
        placement = _detect_gcp_org_placement()
        org_id = str(placement.get("org_id") or "").strip()
        if org_id:
            next_payload["org_id"] = org_id

    labels = next_payload.get("labels")
    if labels is None:
        labels = {}
    if not isinstance(labels, dict):
        labels = {}
    if context_id:
        labels["context"] = context_id
    next_payload["labels"] = labels

    return next_payload


def _render_module_yaml(
    module_ref: str,
    payload: dict[str, Any],
    *,
    source_label: str,
) -> str:
    header = [
        f"# Generated by `hyops module init` for {module_ref}.",
    ]
    if source_label:
        header.append(f"# Base template: {source_label}")
    if module_ref == "org/gcp/project-factory":
        header.append(
            "# project_id, region, billing_account_id, and context_id are prefilled from the env GCP init context when available."
        )
        header.append("# Optional enterprise placement: set exactly one of org_id or folder_id.")
        header.append("# Consumer/trial accounts can omit both.")
    body = yaml.safe_dump(payload, sort_keys=False)
    return "\n".join(header) + "\n" + body


def _write_overlay(dest_path: Path, text: str) -> None:
    write_text_atomic(dest_path, text, mode=0o600)
    os.chmod(dest_path, 0o600)


def add_module_subparser(sp: argparse._SubParsersAction) -> None:
    p = sp.add_parser("module", help="Module helper commands.")
    ssp = p.add_subparsers(dest="module_cmd", required=True)

    i = ssp.add_parser(
        "init",
        help="Materialize an env-scoped module input overlay for operator editing.",
    )
    i.add_argument("--module", dest="module_ref", required=True, help="Module ref, e.g. org/gcp/project-factory.")
    i.add_argument("--root", default=None, help="Override runtime root for module overlay output.")
    i.add_argument("--env", default=None, help="Runtime environment namespace (e.g. dev, shared).")
    i.add_argument(
        "--module-root",
        default="modules",
        help="Module root directory (default: modules from cwd or HYOPS_CORE_ROOT).",
    )
    i.add_argument(
        "--state-instance",
        default="",
        help="Optional state instance name; writes to config/modules/.../instances/<name>.inputs.yml.",
    )
    i.add_argument(
        "--source",
        default="",
        help="Optional example/template path relative to the module directory or absolute path.",
    )
    i.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing runtime module overlay.",
    )
    i.add_argument("--json", action="store_true", help="Emit JSON output.")
    i.set_defaults(_handler=run_init)


def run_init(ns) -> int:
    try:
        require_runtime_selection(
            getattr(ns, "root", None),
            getattr(ns, "env", None),
            command_label="hyops module init",
        )
        module_ref = normalize_module_ref(str(getattr(ns, "module_ref", "") or "").strip())
        if not module_ref:
            raise ValueError("module_ref is required")
        module_root = resolve_module_root(getattr(ns, "module_root", None))
        module_dir = _resolve_module_dir(module_root, module_ref)
        state_instance = normalize_state_instance(str(getattr(ns, "state_instance", "") or "").strip() or None)

        from hyops.runtime.paths import resolve_runtime_paths

        paths = resolve_runtime_paths(getattr(ns, "root", None), getattr(ns, "env", None))
        ensure_layout(paths)
        env_name = str(getattr(ns, "env", "") or "").strip()
        dest_path = rerun_inputs_path(paths.config_dir, module_ref, state_instance=state_instance)
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        if dest_path.exists() and not bool(getattr(ns, "force", False)):
            raise FileExistsError(
                f"module input overlay already exists: {dest_path} "
                "(use --force to overwrite)"
            )

        source_label = ""
        if str(getattr(ns, "source", "") or "").strip():
            source_path = _resolve_source_file(module_dir, str(getattr(ns, "source", "") or ""))
            source_label = str(source_path)
            text = source_path.read_text(encoding="utf-8")
            payload = _load_yaml(source_path)
            if module_ref == "org/gcp/project-factory":
                payload = _enrich_project_factory_payload(payload, paths=paths, env_name=env_name)
                text = _render_module_yaml(module_ref, payload, source_label=source_label)
            _write_overlay(dest_path, text)
        else:
            candidates = _find_example_candidates(module_dir)
            if candidates:
                source_label = str(candidates[0])
                text = candidates[0].read_text(encoding="utf-8")
                payload = _load_yaml(candidates[0])
                if module_ref == "org/gcp/project-factory":
                    payload = _enrich_project_factory_payload(payload, paths=paths, env_name=env_name)
                    text = _render_module_yaml(module_ref, payload, source_label=source_label)
                _write_overlay(dest_path, text)
            else:
                defaults = _defaults_payload(module_dir)
                if module_ref == "org/gcp/project-factory":
                    defaults = _enrich_project_factory_payload(defaults, paths=paths, env_name=env_name)
                _write_overlay(
                    dest_path,
                    _render_module_yaml(
                        module_ref,
                        defaults,
                        source_label=f"{module_dir / 'spec.yml'}#inputs.defaults",
                    ),
                )
                source_label = f"{module_dir / 'spec.yml'}#inputs.defaults"

        out = {
            "module_ref": module_ref,
            "status": "initialized",
            "source": source_label,
            "file": str(dest_path),
        }
        if state_instance:
            out["state_instance"] = state_instance

        if bool(getattr(ns, "json", False)):
            print(json.dumps(out, indent=2, sort_keys=True))
        else:
            suffix = f" state_instance={state_instance}" if state_instance else ""
            print(f"module={module_ref}{suffix} status=initialized")
            print(f"source={source_label}")
            print(f"file={dest_path}")
        return 0
    except Exception as exc:
        print(f"ERR: module init failed: {exc}")
        return OPERATOR_ERROR
