---
# purpose: Role metadata for netbox_service
# maintainer: HybridOps.Tech

galaxy_info:
  role_name: netbox_service
  namespace: hybridops
  author: HybridOps.Tech
  description: Deploy NetBox via Docker Compose.
  license: MIT-0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["9"]
    - name: Ubuntu
      versions: ["all"]
