---
- name: Destroy platform/linux/gns3-lab-archive
  hosts: targets
  become: false
  gather_facts: false

  tasks: []

  post_tasks:
    - name: Write HyOps outputs
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        dest: "{{ hyops_outputs_file }}"
        mode: "0600"
        content: |
          {{ {
            'cap.lab.gns3.archive': 'retained'
          } | to_json }}
