---
# purpose: OS vars shim for RedHat family v10 (compat with upstream geerlingguy.postgresql)
# adr: ADR-0101, ADR-0103
# maintainer: HybridOps.Tech

postgresql_service_upstream_version: "13"
postgresql_service_upstream_data_dir: "/var/lib/pgsql/data"
postgresql_service_upstream_bin_path: "/usr/bin"
postgresql_service_upstream_config_path: "/var/lib/pgsql/data"
postgresql_service_upstream_daemon: postgresql

postgresql_service_upstream_packages:
  - postgresql
  - postgresql-server
  - postgresql-contrib

postgresql_service_upstream_unix_socket_directories_mode: "0755"
postgresql_service_upstream_python_library: python3-psycopg2
